/*
  ____    _____ _ _ _            
 |  _ \  |  ___(_) | |_ ___ _ __ 
 | |_) | | |_  | | | __/ _ \ '__|
 |  _ <  |  _| | | | ||  __/ |   
 |_| \_\ |_|   |_|_|\__\___|_|   
                                 
# A filter plugin that embeds an R interpreter
# Generated by the command: plugin -t filter -d . r_filter
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/Develop/MADS_plugins/r_plugin
# Creation date: 2026-03-23T09:56:26.643+0100
# NOTICE: MADS Version 2.0.2
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <EmbedR.hpp>
#include <variant>
#include "r_plugin_common.hpp"

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "r_filter"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using EmbedR::RInterpreter;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RFilter : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    auto function = _r_interpreter->function("load_data");
    EmbedR::RInterpreter::RValue result;
    try {
      result = function(input);
    } catch (const std::exception& e) {
      _error = e.what();
      return return_type::error;
    }
    if (std::holds_alternative<string>(result)) {
      string return_type_str = std::get<string>(result);
      auto it = RPluginCommon::return_type_map.find(return_type_str);
      if (it != RPluginCommon::return_type_map.end()) {
        return it->second;
      } else {
        _error = "Invalid return type string from load_data(): " + return_type_str;
        return return_type::error;
      }
    } else if (std::holds_alternative<bool>(result)) {
      return std::get<bool>(result) ? return_type::success : return_type::error;
    } else {
      _error = "load_data returned invalid type (expected string or bool)";
      return return_type::error;
    }
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    EmbedR::RInterpreter::RValue result;
    auto function = _r_interpreter->function("process");
    try {
      result = function();
    } catch (const std::exception& e) {
      _error = e.what();
      return return_type::error;
    }
    if (!std::holds_alternative<json>(result)) {
      _error = "Unexpected return type from process()";
      return return_type::error;
    }
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    out = std::get<json>(result);
    if (out.contains("return_type") && out["return_type"].is_string()) {
      auto rt_str = out["return_type"].get<std::string>();
      auto it = RPluginCommon::return_type_map.find(rt_str);
      out.erase("return_type");
      if (it != RPluginCommon::return_type_map.end()) {
        return it->second;
      } else { 
        return return_type::success;
      }
    }
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    Filter::set_params(params);
    RPluginCommon::initialize_r_plugin(
      params,
      _params,
      _r_options,
      _r_interpreter,
      std::vector<std::string>{"load_data", "process"},
      "agent");
    RInterpreter::RValue result;
    try {
      result = _r_interpreter->eval(
          "exists('set_params') && is.function(set_params)");
    } catch (std::exception const &e) {
      throw std::runtime_error("Error checking optional R function 'set_params': " +
                               std::string(e.what()));
    }
    if (std::holds_alternative<bool>(result) && std::get<bool>(result)) {
      auto set_params_func = _r_interpreter->function("set_params");
      set_params_func(params);
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"Using .renv", _r_options.auto_load_current_dir_renv ? "Yes" : "No"},
      {"Output mode", _r_options.output_mode == RInterpreter::OutputMode::Stdout ? "Stdout" : "Buffer"}
    };
  };

private:
  RInterpreter::Options _r_options;
  unique_ptr<RInterpreter> _r_interpreter;
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
MADS_REGISTER_PLUGINS(RFilter);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  try {
    RFilter plugin;
    json params;
    json input, output;

    // Set example values to params
    params["test"] = "value";
    params["use_renv"] = false;
    params["init_script"] = "filter.R";

    // Set the parameters
    plugin.set_params(params);

    // Set input data
    input["value"] = 42;

    // Set input data
    plugin.load_data(input);
    cout << "Input: " << input.dump(2) << endl;

    // Process data
    plugin.process(output);
    cout << "Output: " << output.dump(2) << endl;
  } catch (std::exception const &e) {
    cerr << "r_filter.plugin failed: " << e.what() << endl;
    return 1;
  }

  return 0;
}
