/*
  ____    _____ _ _ _            
 |  _ \  |  ___(_) | |_ ___ _ __ 
 | |_) | | |_  | | | __/ _ \ '__|
 |  _ <  |  _| | | | ||  __/ |   
 |_| \_\ |_|   |_|_|\__\___|_|   
                                 
# A filter plugin that embeds an R interpreter
# Generated by the command: plugin -t filter -d . r_filter
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/Develop/MADS_plugins/r_plugin
# Creation date: 2026-03-23T09:56:26.643+0100
# NOTICE: MADS Version 2.0.2
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <EmbedR.hpp>
#include <variant>
#include "r_plugin_common.hpp"

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "r_filter"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using EmbedR::RInterpreter;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RFilter : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    auto function = _r_interpreter->function("load_data");
    auto result = function(input);
    if (!std::holds_alternative<json>(result)) {
      _error = "Unexpected return type from load_data()";
      return return_type::error;
    }
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    auto function = _r_interpreter->function("process");
    auto result = function(out);
    if (!std::holds_alternative<json>(result)) {
      _error = "Unexpected return type from process()";
      return return_type::error;
    }
    out = std::get<json>(result);
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    Filter::set_params(params);
    RPluginCommon::initialize_r_plugin(
      params,
      _params,
      _r_options,
      _r_interpreter,
      std::vector<std::string>{{"load_data", "process"}},
      "agent");
    auto result = _r_interpreter->eval("exists('set_params') && is.function(set_params)");
    if (std::holds_alternative<bool>(result) && std::get<bool>(result)) {
      auto set_params_func = _r_interpreter->function("set_params");
      set_params_func(params);
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"Using .renv", _r_options.auto_load_current_dir_renv ? "Yes" : "No"},
      {"Output mode", _r_options.output_mode == RInterpreter::OutputMode::Stdout ? "Stdout" : "Buffer"}
    };
  };

private:
  RInterpreter::Options _r_options;
  unique_ptr<RInterpreter> _r_interpreter;
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(RFilter, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  RFilter plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}
