/*
  ____    _____ _ _ _            
 |  _ \  |  ___(_) | |_ ___ _ __ 
 | |_) | | |_  | | | __/ _ \ '__|
 |  _ <  |  _| | | | ||  __/ |   
 |_| \_\ |_|   |_|_|\__\___|_|   
                                 
# A filter plugin that embeds an R interpreter
# Generated by the command: plugin -t filter -d . r_filter
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/Develop/MADS_plugins/r_plugin
# Creation date: 2026-03-23T09:56:26.643+0100
# NOTICE: MADS Version 2.0.2
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <EmbedR.hpp>
#include <variant>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "r_filter"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using EmbedR::RInterpreter;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RFilter : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    // Do something with the input data
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    auto function = _r_interpreter->function("process");
    auto result = function(out);
    if (!std::holds_alternative<json>(result)) {
      _error = "Unexpected return type from process()";
      return return_type::error;
    }
    out = std::get<json>(result);
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    Filter::set_params(params);
    _params["use_renv"] = true;
    _params["r_output_mode"] = "stdout";
    _params.merge_patch(params);
    
    if (_params.value("use_renv", false)) {
      _r_options.auto_load_current_dir_renv = true;
    } else {
      _r_options.auto_load_current_dir_renv = false;
    }

    if (_params["r_output_mode"] == "stdout") {
      _r_options.output_mode = RInterpreter::OutputMode::Stdout;
    } else if (_params["r_output_mode"] == "buffer") {
      _r_options.output_mode = RInterpreter::OutputMode::Buffer;
    } else {
      throw std::runtime_error("Invalid value for r_output_mode. Expected 'stdout' or 'buffer'.");
    }

    try {
      _r_interpreter = make_unique<RInterpreter>(_r_options);
    } catch (const std::exception& e) {
      throw std::runtime_error("Error initializing R interpreter: " + std::string(e.what()));
    }

    if (_params.contains("init_script")) {
      try {
      _r_interpreter->source_script(_params["init_script"].get<std::string>());
      } catch (const std::exception& e) {
        throw std::runtime_error("Error sourcing init_script: " + std::string(e.what()));
      }
    } else {
      throw std::runtime_error("Missing required parameter: init_script");
    }

    const auto result = _r_interpreter->eval("exists('process') & is.function(process)");
    if (!std::holds_alternative<bool>(result) || !std::get<bool>(result)) {
      throw std::runtime_error("The init_script must define a function named process with the appropriate signature for the agent type.");
    }  
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  RInterpreter::Options _r_options;
  unique_ptr<RInterpreter> _r_interpreter;
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(RFilter, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  RFilter plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

