/*
  ____    ____  _       _    
 |  _ \  / ___|(_)_ __ | | __
 | |_) | \___ \| | '_ \| |/ /
 |  _ <   ___) | | | | |   < 
 |_| \_\ |____/|_|_| |_|_|\_\
                             
# A sink plugin that embeds an R interpreter
# Generated by the command: plugin -t sink -d . r_sink
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/Develop/MADS_plugins/r_plugin
# Creation date: 2026-03-23T09:56:39.661+0100
# NOTICE: MADS Version 2.0.2
*/

// Mandatory included headers
#include <sink.hpp>

#include <EmbedR.hpp>
#include <variant>
#include "r_plugin_common.hpp"

// other includes as needed here

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using EmbedR::RInterpreter;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RSink : public Sink<json> {

public:

  // Typically, no need to change this
  string kind() override { return "r_sink"; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    EmbedR::RInterpreter::RValue result;
    auto load_data_func = _r_interpreter->function("load_data");
    try {
      result = load_data_func(input);
    } catch (const std::exception& e) {
      _error = e.what();
      return return_type::error;
    }
    if (std::holds_alternative<string>(result)) {
      string return_type_str = std::get<string>(result);
      auto it = RPluginCommon::return_type_map.find(return_type_str);
      if (it != RPluginCommon::return_type_map.end()) {
        return it->second;
      } else {
        _error = "Invalid return type string from load_data(): " + return_type_str;
        return return_type::error;
      }
    } else if (std::holds_alternative<bool>(result)) {
      return std::get<bool>(result) ? return_type::success : return_type::error;
    } else {
      _error = "load_data returned invalid type (expected string or bool)";
      return return_type::error;
    }
    return return_type::success;
  }

  void set_params(const json &params) override { 
    Sink::set_params(params);
    RPluginCommon::initialize_r_plugin(
      params,
      _params,
      _r_options,
      _r_interpreter,
      "load_data",
      "agent");
    auto result = _r_interpreter->eval("exists('set_params') && is.function(set_params)");
    if (std::holds_alternative<bool>(result) && std::get<bool>(result)) {
      auto set_params_func = _r_interpreter->function("set_params");
      set_params_func(params);
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"Using .renv", _r_options.auto_load_current_dir_renv ? "Yes" : "No"},
      {"Output mode", _r_options.output_mode == RInterpreter::OutputMode::Stdout ? "Stdout" : "Buffer"}
    };
  };

private:
  RInterpreter::Options _r_options;
  unique_ptr<RInterpreter> _r_interpreter;
  
};





/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main_sink(int argc, char const *argv[]) {
  RSink plugin;
  json input, params;
  params["use_renv"] = false;
  params["init_script"] = "sink.R";
  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  input = {{"key1", "value1"}, {"key2", 2}, {"key3", true}};

  // Process data
  plugin.load_data(input);

  return 0;
}
