/*
  ____    ____  _       _    
 |  _ \  / ___|(_)_ __ | | __
 | |_) | \___ \| | '_ \| |/ /
 |  _ <   ___) | | | | |   < 
 |_| \_\ |____/|_|_| |_|_|\_\
                             
# A sink plugin that embeds an R interpreter
# Generated by the command: plugin -t sink -d . r_sink
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/Develop/MADS_plugins/r_plugin
# Creation date: 2026-03-23T09:56:39.661+0100
# NOTICE: MADS Version 2.0.2
*/

// Mandatory included headers
#include <sink.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <EmbedR.hpp>
#include <variant>
#include "r_plugin_common.hpp"

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "r_sink"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using EmbedR::RInterpreter;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RSink : public Sink<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    auto deal_with_data_func = _r_interpreter->function("deal_with_data");
    auto result = deal_with_data_func(input);
    if (!std::holds_alternative<bool>(result) || !std::get<bool>(result)) {
      _error = "deal_with_data returned false or non-boolean value";
      return return_type::error;
    }
    return return_type::success;
  }

  void set_params(const json &params) override { 
    Sink::set_params(params);
    RPluginCommon::initialize_r_plugin(
      params,
      _params,
      _r_options,
      _r_interpreter,
      "deal_with_data",
      "agent");
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"Using .renv", _r_options.auto_load_current_dir_renv ? "Yes" : "No"},
      {"Output mode", _r_options.output_mode == RInterpreter::OutputMode::Stdout ? "Stdout" : "Buffer"}
    };
  };

private:
  RInterpreter::Options _r_options;
  unique_ptr<RInterpreter> _r_interpreter;
  
};



/*
  ____  _             _             _      _                
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __ 
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |   
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|   
                |___/                                      
Enable the class as plugin 
*/
INSTALL_SINK_DRIVER(RSink, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  RSink plugin;
  json input, params;
  
  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.load_data(input);

  return 0;
}
