/*
  ____    ____                           
 |  _ \  / ___|  ___  _   _ _ __ ___ ___ 
 | |_) | \___ \ / _ \| | | | '__/ __/ _ \
 |  _ <   ___) | (_) | |_| | | | (_|  __/
 |_| \_\ |____/ \___/ \__,_|_|  \___\___|
                                         
# A source plugin that embeds an R interpreter
# Generated by the command: plugin -t source r_plugin
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-03-02T10:40:40.526+0100
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <source.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <EmbedR.hpp>
#include <variant>
#include "r_plugin_common.hpp"

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "r_source"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using EmbedR::RInterpreter;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RSource : public Source<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;

    EmbedR::RInterpreter::RValue result;
    try {
      result = _r_interpreter->eval("get_output()");
    } catch (const std::exception& e) {
      _error = e.what();
      return return_type::retry;
    }
    if (std::holds_alternative<nlohmann::json>(result)) {
      out = std::get<nlohmann::json>(result);
    } else {
      _error = "Unexpected return type from get_output()";
      return return_type::retry;
    }
    return return_type::success;
  }

  void set_params(const json &params) override {
    Source::set_params(params);
    RPluginCommon::initialize_r_plugin(
      params,
      _params,
      _r_options,
      _r_interpreter,
      "get_output",
      "agent");
    auto result = _r_interpreter->eval("exists('set_params') && is.function(set_params)");
    if (std::holds_alternative<bool>(result) && std::get<bool>(result)) {
      auto set_params_func = _r_interpreter->function("set_params");
      set_params_func(params);
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"Using .renv", _r_options.auto_load_current_dir_renv ? "Yes" : "No"},
      {"Output mode", _r_options.output_mode == RInterpreter::OutputMode::Stdout ? "Stdout" : "Buffer"}
    };
  };

private:
  // Define the fields that are used to store internal resources
  RInterpreter::Options _r_options;
  unique_ptr<RInterpreter> _r_interpreter;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SOURCE_DRIVER(RSource, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  RSource plugin;
  json output, params;

  // Set example values to params
  params["use_renv"] = true;
  params["init_script"] = "source.R";

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.get_output(output);
  cout << "Output: " << output << endl;
  plugin.get_output(output);
  cout << "Output: " << output << endl;
  plugin.get_output(output);
  cout << "Output: " << output << endl;
  plugin.get_output(output);
  cout << "Output: " << output << endl;

  return 0;
}
